name = "pages"
type = "webpack"
account_id = "6f3fae9cff251a89f334f9debec204f1"
webpack_config = "./worker/webpack.config.js"
compatibility_date = "2021-09-29"

[site]
bucket = "./dist/client"
entry-point = "./worker"

[env.development]
name = "pages-dev"
workers_dev = true
vars = { STAGE = "development", SITE_URL = "" }

[env.production]
name = "pages-prod"
routes = ["pub.raindrop.io/*"]
vars = { STAGE = "production", SITE_URL = "https://pub.raindrop.io" }