name = "pages"
type = "webpack"
account_id = "6f3fae9cff251a89f334f9debec204f1"
workers_dev = true
webpack_config = "./worker/webpack.config.js"
compatibility_date = "2021-09-29"

[site]
bucket = "./dist/client"
entry-point = "./worker"